version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
    networks:
      - app-network

  service1:
    build:
      context: ./service1
    ports:
      - "8001:8001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  service2:
    build:
      context: ./service2
    ports:
      - "8002:8002"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  app-network:
    driver: bridge

